use std::fmt::Display;

use rand::RngExt;

#[derive(Debug, Copy, Clone, PartialEq)]
pub enum Glyph {
    Alerion,
    Allocamelus,
    Alphyn,
    Amphiptere,
    Annulet,
    Argent,
    Aurora,
    Axe,
    Azure,
    Bar,
    Base,
    Basilisk,
    Basket,
    Bear,
    Bee,
    Bend,
    Bezant,
    Biscione,
    Boar,
    Bordure,
    Bourchier,
    Bowen,
    BowenWake,
    Bull,
    Caldron,
    Camelopard,
    Canton,
    Carbuncle,
    Cavendish,
    Chevron,
    Chief,
    Chollima,
    Clarion,
    Cockatrice,
    Componee,
    Cossack,
    Crapaudy,
    Crescent,
    Cross,
    Crow,
    Crozier,
    Dacre,
    Dagger,
    Dog,
    Dolphin,
    Dove,
    Dragon,
    Eagle,
    Emmet,
    Enfield,
    Ermine,
    Esquarre,
    Esquire,
    Fess,
    Fillet,
    Fire,
    Flaunch,
    Fountain,
    Garuda,
    Ged,
    Gore,
    Goutte,
    Griffin,
    Gules,
    Gusset,
    Gyron,
    Hamade,
    Hammer,
    Harpy,
    Harrington,
    Hastings,
    Heart,
    Heneage,
    Hinckaert,
    Hind,
    Hippocampus,
    Hippogriff,
    Hound,
    Hungerford,
    Inescutcheon,
    Kangaroo,
    Keythong,
    Lacy,
    Lampago,
    Leopard,
    Lindworm,
    Lion,
    Lozenge,
    Lucy,
    Manticore,
    Martlet,
    Mermaid,
    Mill,
    Mount,
    Musimon,
    Oak,
    Or,
    Orle,
    Ormonde,
    Ouroboros,
    Ox,
    Pale,
    Pall,
    Pantheon,
    Panther,
    Pean,
    Pegasus,
    Pelican,
    Phoenix,
    Pike,
    Pile,
    Pizzle,
    Portcullis,
    Potent,
    Purpure,
    Quatrefoil,
    Reremouse,
    Rose,
    Roundel,
    Sable,
    Salamander,
    Saltire,
    Savoy,
    Scallop,
    Seeblatt,
    Serpent,
    Shamrock,
    Side,
    Stafford,
    Stag,
    Star,
    SunTrident,
    Swan,
    Sword,
    Szaszor,
    Thistle,
    Trefoil,
    Tristram,
    Turnip,
    Tyger,
    Unicorn,
    Vair,
    Vert,
    Vol,
    Wake,
    Waterlily,
    Wolf,
    Wolfsangel,
    Woodwose,
    Wyvern,
    Yale,
}

const GLYPHS: &[Glyph] = &[
    Glyph::Alerion,
    Glyph::Allocamelus,
    Glyph::Alphyn,
    Glyph::Amphiptere,
    Glyph::Annulet,
    Glyph::Argent,
    Glyph::Aurora,
    Glyph::Axe,
    Glyph::Azure,
    Glyph::Bar,
    Glyph::Base,
    Glyph::Basilisk,
    Glyph::Basket,
    Glyph::Bear,
    Glyph::Bee,
    Glyph::Bend,
    Glyph::Bezant,
    Glyph::Biscione,
    Glyph::Boar,
    Glyph::Bordure,
    Glyph::Bourchier,
    Glyph::Bowen,
    Glyph::BowenWake,
    Glyph::Bull,
    Glyph::Caldron,
    Glyph::Camelopard,
    Glyph::Canton,
    Glyph::Carbuncle,
    Glyph::Cavendish,
    Glyph::Chevron,
    Glyph::Chief,
    Glyph::Chollima,
    Glyph::Clarion,
    Glyph::Cockatrice,
    Glyph::Componee,
    Glyph::Cossack,
    Glyph::Crapaudy,
    Glyph::Crescent,
    Glyph::Cross,
    Glyph::Crow,
    Glyph::Crozier,
    Glyph::Dacre,
    Glyph::Dagger,
    Glyph::Dog,
    Glyph::Dolphin,
    Glyph::Dove,
    Glyph::Dragon,
    Glyph::Eagle,
    Glyph::Emmet,
    Glyph::Enfield,
    Glyph::Ermine,
    Glyph::Esquarre,
    Glyph::Esquire,
    Glyph::Fess,
    Glyph::Fillet,
    Glyph::Fire,
    Glyph::Flaunch,
    Glyph::Fountain,
    Glyph::Garuda,
    Glyph::Ged,
    Glyph::Gore,
    Glyph::Goutte,
    Glyph::Griffin,
    Glyph::Gules,
    Glyph::Gusset,
    Glyph::Gyron,
    Glyph::Hamade,
    Glyph::Hammer,
    Glyph::Harpy,
    Glyph::Harrington,
    Glyph::Hastings,
    Glyph::Heart,
    Glyph::Heneage,
    Glyph::Hinckaert,
    Glyph::Hind,
    Glyph::Hippocampus,
    Glyph::Hippogriff,
    Glyph::Hound,
    Glyph::Hungerford,
    Glyph::Inescutcheon,
    Glyph::Kangaroo,
    Glyph::Keythong,
    Glyph::Lacy,
    Glyph::Lampago,
    Glyph::Leopard,
    Glyph::Lindworm,
    Glyph::Lion,
    Glyph::Lozenge,
    Glyph::Lucy,
    Glyph::Manticore,
    Glyph::Martlet,
    Glyph::Mermaid,
    Glyph::Mill,
    Glyph::Mount,
    Glyph::Musimon,
    Glyph::Oak,
    Glyph::Or,
    Glyph::Orle,
    Glyph::Ormonde,
    Glyph::Ouroboros,
    Glyph::Ox,
    Glyph::Pale,
    Glyph::Pall,
    Glyph::Pantheon,
    Glyph::Panther,
    Glyph::Pean,
    Glyph::Pegasus,
    Glyph::Pelican,
    Glyph::Phoenix,
    Glyph::Pike,
    Glyph::Pile,
    Glyph::Pizzle,
    Glyph::Portcullis,
    Glyph::Potent,
    Glyph::Purpure,
    Glyph::Quatrefoil,
    Glyph::Reremouse,
    Glyph::Rose,
    Glyph::Roundel,
    Glyph::Sable,
    Glyph::Salamander,
    Glyph::Saltire,
    Glyph::Savoy,
    Glyph::Scallop,
    Glyph::Seeblatt,
    Glyph::Serpent,
    Glyph::Shamrock,
    Glyph::Side,
    Glyph::Stafford,
    Glyph::Stag,
    Glyph::Star,
    Glyph::SunTrident,
    Glyph::Swan,
    Glyph::Sword,
    Glyph::Szaszor,
    Glyph::Thistle,
    Glyph::Trefoil,
    Glyph::Tristram,
    Glyph::Turnip,
    Glyph::Tyger,
    Glyph::Unicorn,
    Glyph::Vair,
    Glyph::Vert,
    Glyph::Vol,
    Glyph::Wake,
    Glyph::Waterlily,
    Glyph::Wolf,
    Glyph::Wolfsangel,
    Glyph::Woodwose,
    Glyph::Wyvern,
    Glyph::Yale,
];

impl Glyph {

    pub fn random() -> Glyph {
        let mut rng = rand::rng();

        GLYPHS[rng.random_range(0..GLYPHS.len())]
    }
}

impl Display for Glyph {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match &self {
            Glyph::Alerion => "Alerion",
            Glyph::Allocamelus => "Allocamelus",
            Glyph::Alphyn => "Alphyn",
            Glyph::Amphiptere => "Amphiptere",
            Glyph::Annulet => "Annulet",
            Glyph::Argent => "Argent",
            Glyph::Aurora => "Aurora",
            Glyph::Axe => "Axe",
            Glyph::Azure => "Azure",
            Glyph::Bar => "Bar",
            Glyph::Base => "Base",
            Glyph::Basilisk => "Basilisk",
            Glyph::Basket => "Basket",
            Glyph::Bear => "Bear",
            Glyph::Bee => "Bee",
            Glyph::Bend => "Bend",
            Glyph::Bezant => "Bezant",
            Glyph::Biscione => "Biscione",
            Glyph::Boar => "Boar",
            Glyph::Bordure => "Bordure",
            Glyph::Bourchier => "Bourchier",
            Glyph::Bowen => "Bowen",
            Glyph::BowenWake => "BowenWake",
            Glyph::Bull => "Bull",
            Glyph::Caldron => "Caldron",
            Glyph::Camelopard => "Camelopard",
            Glyph::Canton => "Canton",
            Glyph::Carbuncle => "Carbuncle",
            Glyph::Cavendish => "Cavendish",
            Glyph::Chevron => "Chevron",
            Glyph::Chief => "Chief",
            Glyph::Chollima => "Chollima",
            Glyph::Clarion => "Clarion",
            Glyph::Cockatrice => "Cockatrice",
            Glyph::Componee => "Componee",
            Glyph::Cossack => "Cossack",
            Glyph::Crapaudy => "Crapaudy",
            Glyph::Crescent => "Crescent",
            Glyph::Cross => "Cross",
            Glyph::Crow => "Crow",
            Glyph::Crozier => "Crozier",
            Glyph::Dacre => "Dacre",
            Glyph::Dagger => "Dagger",
            Glyph::Dog => "Dog",
            Glyph::Dolphin => "Dolphin",
            Glyph::Dove => "Dove",
            Glyph::Dragon => "Dragon",
            Glyph::Eagle => "Eagle",
            Glyph::Emmet => "Emmet",
            Glyph::Enfield => "Enfield",
            Glyph::Ermine => "Ermine",
            Glyph::Esquarre => "Esquarre",
            Glyph::Esquire => "Esquire",
            Glyph::Fess => "Fess",
            Glyph::Fillet => "Fillet",
            Glyph::Fire => "Fire",
            Glyph::Flaunch => "Flaunch",
            Glyph::Fountain => "Fountain",
            Glyph::Garuda => "Garuda",
            Glyph::Ged => "Ged",
            Glyph::Gore => "Gore",
            Glyph::Goutte => "Goutte",
            Glyph::Griffin => "Griffin",
            Glyph::Gules => "Gules",
            Glyph::Gusset => "Gusset",
            Glyph::Gyron => "Gyron",
            Glyph::Hamade => "Hamade",
            Glyph::Hammer => "Hammer",
            Glyph::Harpy => "Harpy",
            Glyph::Harrington => "Harrington",
            Glyph::Hastings => "Hastings",
            Glyph::Heart => "Heart",
            Glyph::Heneage => "Heneage",
            Glyph::Hinckaert => "Hinckaert",
            Glyph::Hind => "Hind",
            Glyph::Hippocampus => "Hippocampus",
            Glyph::Hippogriff => "Hippogriff",
            Glyph::Hound => "Hound",
            Glyph::Hungerford => "Hungerford",
            Glyph::Inescutcheon => "Inescutcheon",
            Glyph::Kangaroo => "Kangaroo",
            Glyph::Keythong => "Keythong",
            Glyph::Lacy => "Lacy",
            Glyph::Lampago => "Lampago",
            Glyph::Leopard => "Leopard",
            Glyph::Lindworm => "Lindworm",
            Glyph::Lion => "Lion",
            Glyph::Lozenge => "Lozenge",
            Glyph::Lucy => "Lucy",
            Glyph::Manticore => "Manticore",
            Glyph::Martlet => "Martlet",
            Glyph::Mermaid => "Mermaid",
            Glyph::Mill => "Mill",
            Glyph::Mount => "Mount",
            Glyph::Musimon => "Musimon",
            Glyph::Oak => "Oak",
            Glyph::Or => "Or",
            Glyph::Orle => "Orle",
            Glyph::Ormonde => "Ormonde",
            Glyph::Ouroboros => "Ouroboros",
            Glyph::Ox => "Ox",
            Glyph::Pale => "Pale",
            Glyph::Pall => "Pall",
            Glyph::Pantheon => "Pantheon",
            Glyph::Panther => "Panther",
            Glyph::Pean => "Pean",
            Glyph::Pegasus => "Pegasus",
            Glyph::Pelican => "Pelican",
            Glyph::Phoenix => "Phoenix",
            Glyph::Pike => "Pike",
            Glyph::Pile => "Pile",
            Glyph::Pizzle => "Pizzle",
            Glyph::Portcullis => "Portcullis",
            Glyph::Potent => "Potent",
            Glyph::Purpure => "Purpure",
            Glyph::Quatrefoil => "Quatrefoil",
            Glyph::Reremouse => "Reremouse",
            Glyph::Rose => "Rose",
            Glyph::Roundel => "Roundel",
            Glyph::Sable => "Sable",
            Glyph::Salamander => "Salamander",
            Glyph::Saltire => "Saltire",
            Glyph::Savoy => "Savoy",
            Glyph::Scallop => "Scallop",
            Glyph::Seeblatt => "Seeblatt",
            Glyph::Serpent => "Serpent",
            Glyph::Shamrock => "Shamrock",
            Glyph::Side => "Side",
            Glyph::Stafford => "Stafford",
            Glyph::Stag => "Stag",
            Glyph::Star => "Star",
            Glyph::SunTrident => "SunTrident",
            Glyph::Swan => "Swan",
            Glyph::Sword => "Sword",
            Glyph::Szaszor => "Szaszor",
            Glyph::Thistle => "Thistle",
            Glyph::Trefoil => "Trefoil",
            Glyph::Tristram => "Tristram",
            Glyph::Turnip => "Turnip",
            Glyph::Tyger => "Tyger",
            Glyph::Unicorn => "Unicorn",
            Glyph::Vair => "Vair",
            Glyph::Vert => "Vert",
            Glyph::Vol => "Vol",
            Glyph::Wake => "Wake",
            Glyph::Waterlily => "Waterlily",
            Glyph::Wolf => "Wolf",
            Glyph::Wolfsangel => "Wolfsangel",
            Glyph::Woodwose => "Woodwose",
            Glyph::Wyvern => "Wyvern",
            Glyph::Yale => "Yale",
        };

        write!(f, "{s}")
    }
}